### ISSUE TITLE
custom view set to 2 weeks — some merged events disappear 

### ISSUE THREAD

**Issue by ezdub** [coedit/gcal-rainbow-surf#11]
Midge Stocker gave a 4 star review and said:
"Visually great, but I found that some merged events just disappear from my calendar altogether instead of being merged. This happens when I use a custom view set to 2 weeks, which is my preferred view."

I'm unable to reproduce this in my tests, will request further info from Midge.
We're looking for steps to reproduce this issue so we can diagnose it, we need to figure out if there is something unique about those events that disappear which triggers this bug.

**Comment by ezdub** [comment]
can't reproduce it to fix it

**Comment by ezdub** [comment]
there was a repeated code pattern of hiding hidden elements fixed in #17 which would have resolved this bug

**Comment by ezdub** [comment]
there was a repeated code pattern of hiding hidden elements fixed in #17  which would have resolved this bug

**Comment by a-e-f** [comment]
I'm still having this issue—some merged events disappear, regardless of calendar view. They display for a split second after reloading the calendar and then disappear.

**Comment by ezdub** [comment]
Hi, thanks for reporting this. Can you confirm this is only happening with custom view set to two weeks?

It's also very helpful if you can provide any other steps to recreate the issue over here so I can debug.  Does it only happen on short event names / long names, etc?
Thanks!

**Comment by a-e-f** [comment]
No, it's happening with any calendar view—week, day, 4 days. The particular events that prompted me to post this issue are flights—events generated from flight confirmation emails.

**Comment by ezdub** [comment]
Great clues, thank you for responding.
It is curious how these autogenerated events would show on more than one
calendar since presumably the flight confirmation email only goes to one
address.

This may be like duplicate birthday events where the solution is to set
only one account to show these types of automated events and turn off the
feature on the other/s.

**Comment by a-e-f** [comment]
In some cases they're manually copied from one calendar to another and in other cases the flight itinerary is sent from the airline to both email accounts. This is because I need the flights to be visible to people who have access to each calendar (but not both).

**Comment by ezdub** [comment]
Hmm. Can you see any difference in the calendar event name in these cases?

Currently the extension’s duplicate removal only triggers with exactly
matching even names.

**Comment by a-e-f** [comment]
The event names are exactly the same.

**Comment by ezdub** [comment]
I haven’t been able to reproduce this behavior on my end yet, so I’m still
gathering clues about what might be causing it.

One possibility we haven’t explored is a conflict with another extension.
To test this, try going to chrome://extensions/ and temporarily turning off
all extensions except “Merge duplicate Google Calendar events…”. Then,
reload your Google Calendar and see if the issue persists.

If the issue disappears, you can re-enable your extensions one at a time to
see which one brings the problem back. Identifying a specific extension
conflict will help me investigate further.

If the problem continues even with all other extensions off, could you
share the exact steps that lead to the issue on your end? That would help
me replicate it more precisely.
